version: "3.8"

services:
  geodescriber:
    container_name: geodescriber-develop
    build: .
    env_file:
      - .env
    ports:
      - "4501:4501"
    command: start
    volumes:
      - ./geodescriber:/opt/geodescriber/geodescriber
    restart: always
    links:
      - redis
  redis:
    image: redis
    restart: always

networks:
  default:
    external:
      name: control-tower_controltower
